language: php

php:
  - 7.1

notifications:
  email:
    - stumpdenmark@hotmail.com

#stop travis mysql
before_install:
  - sudo service mysql stop

script:
  - cd ./wordpress/wp-content/themes/kbharkiv
  - yarn install
  - yarn build:production

deploy:
  provider: script
  script: bash ${TRAVIS_BUILD_DIR}/trigger-deploy.sh master $TRAVIS_TOKEN
  skip_cleanup: true
  on:
    branch: master

