language: php

php:
  - 7.1

notifications:
  email:
    - stumpdenmark@hotmail.com

#stop travis mysql
before_install:
  - sudo service mysql stop

script:
  - cd ./wordpress/wp-content/themes/kbharkiv
  - yarn install
  - yarn build:production

deploy:
  - provider: script
    script: bash ${TRAVIS_BUILD_DIR}/trigger-deploy.sh master $TRAVIS_TOKEN
    skip_cleanup: true
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^(feature-docker|master)$
  - provider: s3
    access_key_id: ${S3_AWS_ACCESS_KEY}
    secret_access_key: ${S3_AWS_SECRET_ACCESS_KEY}
    bucket: kbharkiv-wordpress-theme
    local-dir: ${TRAVIS_BUILD_DIR}/wordpress/wp-content/themes/kbharkiv
    glob: "{,resources/,resources/**/,dist/,dist/**/,config/,config/**/,app/,app/**/,!(node_modules)/**/}*.*"
    region: eu-west-1
    on:
      repo: CopenhagenCityArchives/kbharkiv-wordpress-theme
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^(feature-docker|master)$
    cleanup: false
    edge: true
  - provider: elasticbeanstalk
    access_key_id: ${EB_AWS_ACCESS_KEY_ID}
    secret_access_key: ${EB_AWS_SECRET_ACCESS_KEY}
    region: eu-west-1
    app: kbharkiv-cms
    env: kbharkiv-cms-dev
    bucket: elasticbeanstalk-eu-west-1-282251075226
    edge: true
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^(feature-docker)$